name: CI

on:
  pull_request:
    branches: [main]

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node: ['10', '12', '14', '15', '16']
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn test
